import { form, get, route } from 'remix/routes'

export const routes = route({
  assets: get('/assets/*path'),
  home: '/',
  services: '/services',
  servicesSocialMedia: get('/services/social-media'),
  servicesPerformanceAds: get('/services/performance-ads'),
  servicesDigitalPr: get('/services/digital-pr'),
  servicesProduction: get('/services/production'),
  servicesWebSolutions: get('/services/web-solutions'),
  servicesDesignCopy: get('/services/design-copy'),
  ourWork: '/our-work',
  ourWorkCaseStudies: get('/our-work/case-studies'),
  ourWorkClientResults: get('/our-work/client-results'),
  ourWorkSuccessStories: get('/our-work/success-stories'),
  ourWorkIndustryExpertise: get('/our-work/industry-expertise'),
  blogs: get('/blogs'),
  blogPost: get('/blogs/:slug'),
  aboutUs: '/about-us',
  aboutUsOurCompany: get('/about-us/our-company'),
  aboutUsOurMission: get('/about-us/our-mission'),
  aboutUsWhyChooseUs: get('/about-us/why-choose-us'),
  aboutUsCareers: get('/about-us/careers'),
  getProposal: get('/get-proposal'),
  contact: get('/contact'),
  privacy: get('/privacy'),
  terms: get('/terms'),
  locations: get('/locations'),
  locationPakistanIslamabad: get('/locations/pakistan/islamabad'),
})

